input {
  kafka {
    bootstrap_servers => "redpanda:9092"
    topics_pattern => "logs\..*"
    group_id => "logstash-logs"
    client_id => "logstash"
    codec => json
    auto_offset_reset => "latest"
  }
}
