filter {
  # Normalisation minimale ECS (exemple)
  if ![@timestamp] {
    mutate { add_field => { "@timestamp" => "%{{TIME_NOW}}" } }
  }

  # Champs requis (exemples)
  if ![service][name] and [service_name] {
    mutate { add_field => { "[service][name]" => "%{service_name}" } }
  }

  # Exemple grok (si message non json structuré)
  if [message] and ![event][dataset] {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:tmp_ts} %{LOGLEVEL:log.level} %{GREEDYDATA:msg}" }
      tag_on_failure => ["_grokparsefailure"]
      patterns_dir => ["/usr/share/logstash/patterns"]
    }
    mutate {
      rename => { "msg" => "message" }
      remove_field => ["tmp_ts"]
    }
  }

  # Routing dataset
  if ![event][dataset] and [topic] {
    mutate { add_field => { "[event][dataset]" => "%{topic}" } }
  }
}
