output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[event][dataset]}-%{+YYYY.MM.dd}"
  }

  # Index DQ / parsing failures
  if "_grokparsefailure" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logs.dq.parsefail-%{+YYYY.MM.dd}"
    }
  }

  stdout { codec => rubydebug }
}
